version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1234
      POSTGRES_DB: attendance_system
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432" 
  web:
   image: biometric_attendance
   depends_on:
      - postgres
   ports:
      - "3000:3000"
volumes:
  pgdata:

